name: IMAS Standard Name
description: Propose an IMAS Standard Name addition or modification.
labels: standard-name

body:
  - type: markdown
    attributes:
      value: |
        Guidelines for the construction of IMAS Standard Names can be found [here](https://github.com/iterorganization/IMAS-Standard-Names/blob/main/docs/guidelines.md). These guidelines should be followed when proposing a new Standard Name.
        
  - type: input
    id: name
    attributes:
      label: name
      description: |
        Standard names consist of lower case letters, digits and underscores,
        and begin with a letter. Upper case is not used.
      placeholder: ex. poloidal_flux
    validations:
      required: true

  - type: input
    id: units
    attributes:
      label: units
      description: |
        Define SI units unless an alternative is widely used in the community.
        note: e (elementary charge unit), u (Dalton / atomic mass unit),
        and eV for electron/ion/neutral temperatures
      placeholder: Wb
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: documentation
      description: Documentation for the proposed Standard Name.
      placeholder: |
        Poloidal flux. Integral of magnetic field passing through a contour
        defined by the intersection of a flux surface passing through the point
        of interest and a $Z=\mathrm{constant}$ plane. The surface normal is in
        the same direction as increasing
        [`vertical_distance`](#vertical_distance).

        $$
        \psi_{pol} = \oint_S \textbf{B} \cdot d\textbf{S}
        $$
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: tags
      description: Comma seperated list of tags.
      placeholder: flux-coordinates, equilibrium/time_slice/profiles_2d/psi
    validations:
      required: false

  - type: checkboxes
    id: options
    attributes:
      label: options
      options:
        - label: This proposal is ready to commit to the Standard Names repository.
