name: IMAS Standard Name
title: Standard Name Proposal
description: Propose an IMAS Standard Name addition or modification.
labels: standard-name

body:
  - type: markdown
    attributes:
      value: |
        Issues submitted with the default title will be automatically labeled with the given Standard Name.

  - type: input
    id: name
    attributes:
      label: Standard Name
      description: |
        Standard names consist of lower case letters, digits and underscores, begin with a letter, and must not contain whitespace. Guidelines for the construction of IMAS Standard Names can be found [here](https://github.com/iterorganization/IMAS-Standard-Names/blob/main/docs/guidelines.md).
      placeholder: ex. radial_magnetic_field_due_to_plasma_current
    validations:
      required: true

  - type: input
    id: units
    attributes:
      label: Units
      description: |
        Use SI units unless an alternative is widely adopted by the community. 
        Enter dimensionless if the physical quantity is dimensionless 
        and none if Standard Name is unitless.
        note: e (elementary charge unit), u (Dalton / atomic mass unit), 
        and eV for electron/ion/neutral temperatures
      placeholder: T
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Documentation for the proposed Standard Name.
      placeholder: |
        The radial component of the magnetic field due to electrical current flowing in the plasma.
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: A comma separated list of tags.
      placeholder: equilibrium, magnetic_field
    validations:
      required: false

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: This proposal overwrites a duplicate Standard Name.

  - type: markdown
    attributes:
      value: |
        ### Review Process
        Issues submitted using the IMAS Standard Name template will be automatically processed by a GitHub Actions workflow. This workflow will check that the proposed Standard Name is compliant with the Fusion Conventions guidelines and, if the overwrite flag is not set, unique.

        The Standard Name author should ensure that at least one reviewer is assigned to this issue. The review is concluded when a reviewer with sufficient privileges affixes the `approve` label to the issue.

        Valid Standard Names will be committed to the `submit` branch. A pull request to the `develop` branch will be raised or updated. Batches of Standard Names will be pushed from the `develop` branch to the `main` branch as tagged commits.
