name: commit-issue
description: Commit valid Standard Name to branch.

inputs:
  standard-name:
    description: "The proposed Standard Name."
    required: true
  valid-commit:
    description: "A boolean flag indicating if the proposal is ready to commit."
    required: true
  standard-name-entry:
    description: "Proposed Standard Name entry."
    required: true

runs:
  using: "composite"
  steps:
    - name: Create PR
      id: create_pr
      if: inputs.valid-commit == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        branch: develop
        title: Add **${{ inputs.standard-name }}** to standardnames.yml
        body: ${{ inputs.standard-name-entry }}

    - name: Close issue
      if: steps.create_pr.outcome == 'success'
      uses: peter-evans/close-issue@v1
      with:
        comment: Merged **${{ inputs.standard-name }}** with standardnames.yml.
