name: commit-issue
description: Commit valid Standard Name to branch.

inputs:
  standard-name:
    description: "The proposed Standard Name."
    required: true
  standard-name-entry:
    description: "Proposed Standard Name entry."
    required: true
  base-branch:
    description: "GitHub actions base branch."
    required: true
  topic-branch:
    description: "GitHub actions development branch."
    required: true

runs:
  using: "composite"
  steps:
    - name: Commit Standard Name proposal
      id: merge-standard-name
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # merge standardnames.yml with edits on topic branch
        git fetch origin ${{ inputs.topic-branch }}:${{ inputs.topic-branch }}
        git show ${{ inputs.base-branch }}:standardnames.yml > base_standardnames.yml
        git show ${{ inputs.topic-branch }}:standardnames.yml > topic_standardnames.yml
        git merge-file standardnames.yml base_standardnames.yml topic_standardnames.yml

        # commit standardnames.yml to base branch
        git add standardnames.yml
        git commit -m "${{ inputs.standard-name }} Standard Name entry."
        git stash

        # switch to topic branch, checkout standardnames.yml, and push
        git switch ${{ inputs.topic-branch }}
        git checkout ${{ inputs.base-branch }} -- standardnames.yml
        git push --set-upstream origin ${{ inputs.topic-branch }}

        # switch back to base branch and pop stash
        git switch ${{ inputs.base-branch }}
        git stash pop

    - name: Close issue
      uses: peter-evans/close-issue@v1
      with:
        comment: Pushed **${{ inputs.standard-name }}** to the ${{ inputs.topic-branch }} branch.
