on:
  workflow_call:

#permissions:
#  contents: write
#  pull-requests: write

jobs:
  label-issue:
    uses: ./.github/workflows/label-issue.yml

  commit-issue:
    runs-on: ubuntu-latest
    needs: label-issue

    steps:
      - uses: actions/checkout@v3

      # - run: node submission.js

      # - run: yarn

      # - run: node ./update.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - run: node ./generate-readme.js

      # - run: |
      #       git config user.email "github@stefanbuck.com"
      #       git config user.name "Stefan Buck"
      #       git add README.md data.json
      #       git diff-index --quiet HEAD || git commit -m "Add new list item"

      - run: git push
      - name: Echo dir
        run: echo -e $(ls -ltr)

      - name: Create PR
        id: create_pr
        if: ${{ needs.label-issue.outputs.commit-flag == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          branch: develop
          title: Add **${{ needs.label-issue.outputs.standard-name }}** to standardnames.yml
          body: ${{ needs.label-issue.outputs.commit-message }}

      - name: Close issue
        if: steps.create_pr.outcome == 'success'
        uses: peter-evans/close-issue@v1
        with:
          comment: Merged **${{ needs.label-issue.outputs.standard-name }}** with standardnames.yml.
